name: DefocusGAN_train
use_tb_logger: true
model:  DefocusGAN

dataset:         
  train:
    name: train
    dataroot: ~ #for your dataset
    filter:
    trainpairs: ~ #for your dataset file
    batch_size: 4
    image_size: 512
    max_iter: 40
    iter_size: 1
    workers: 4
    left_name: train_l/source
    right_name: train_r/source
    combine_name: train_c/target
    combine_source_name: train_c/source
    blur_name: ~ #use learnable BK python file to generate defocus map 
  
  val:
    name: val
    dataroot: ~
    batch_size: 1
    workers: 1
    left_name: val_l/source
    right_name: val_r/source
    combine_name: val_c/target
    combine_source_name: val_c/source
    blur_name: val_Gb/source
    
  test:
    name: test
    dataroot:  ~
    batch_size: 1
    workers: 1
    left_name: test_l/source
    right_name: test_r/source
    combine_name: test_c/target
    combine_source_name: test_c/source
    blur_name: test_Gb/source

network_G:
  in_nc: 3
  block_num: 2
  init: xavier
  hidden_channels: 128
  K: 4

path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~ 

logger:
  print_freq: 10
  save_checkpoint_freq: 3 #!!float 5e3

train:
  lr: !!float 2e-4
  beta1: 0.9
  beta2: 0.999
  max_grad_norm: 20
  max_grad_clip: 20
  niter: 500000
  epoch: 91

  lr_steps: [30, 60, 90,105,120,135,150]
  lr_gamma: 0.5


  val_freq: 20 #!!float 5e3
  kernel_freq: 1 #!!float 5e3
  manual_seed: 17
